version: 2

project_name: terminal-wingman

before:
  hooks:
    - go mod tidy

builds:
  - id: terminal-wingman
    main: ./cmd
    binary: terminal-wingman
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  # Archive for Linux and Mac (tar.gz)
  - id: nix
    builds:
      - terminal-wingman
    formats:
      - tar.gz
    goosandarch:
      - linux_amd64
      - linux_arm64
      - darwin_amd64
      - darwin_arm64
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

  # Archive for Windows (zip)
  - id: windows
    builds:
      - terminal-wingman
    formats:
      - zip
    goosandarch:
      - windows_amd64
      - windows_arm64
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
